import "~/styles/globals.scss";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import WindowsStateProvider from "./providers/windows-state.provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-[100vh] w-[100vw] overflow-hidden bg-black font-sans antialiased">
        <TRPCReactProvider>
          <WindowsStateProvider>{children}</WindowsStateProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
